channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - mlflow
  - sklearn
  - cloudpickle==1.6.0
  - boto3
  - transformers>=4.0.0
  - pandas
  - torchvision>=0.9.1
  - torch>=1.9.0
  - torchtext==0.10.0
  - pytorch-lightning==1.5.1
